font_family FiraCode Nerd Font Mono
font_size 16

include kitty-theme.conf

allow_remote_control yes
confirm_os_window_close 0
enabled_layouts splits:split_axis=horizontal
kitty_mod ctrl+shift
macos_quit_when_last_window_closed no
macos_show_window_title_in window
# integration is sourced manually in zshrc
shell_integration no-rc
sync_to_monitor yes
tab_bar_style powerline

map ctrl+a>- launch --location=hsplit --cwd=current
map ctrl+a>\ launch --location=vsplit --cwd=current
map ctrl+a>c new_tab
map ctrl+a>down neighboring_window down
map ctrl+a>left neighboring_window left
map ctrl+a>n next_tab
map ctrl+a>p previous_tab
map ctrl+a>right neighboring_window right
map ctrl+a>up neighboring_window up
map ctrl+a>x close_window
map kitty_mod+a>backspace change_font_size all 0
map kitty_mod+a>equal change_font_size all +2.0
map kitty_mod+a>kp_add change_font_size all +2.0
map kitty_mod+a>kp_subtract change_font_size all -2.0
map kitty_mod+a>minus change_font_size all -2.0
map kitty_mod+a>plus change_font_size all +2.0
